const songs = [
    {songName: "Annabelle", artist: "Creeper", lyrics: "annabelle we're both going to hell you're gonna love the clientele cheap rent and the climate's swell annabelle i've been drunk since half past twelve don't bring me down don't bring me down"},
    {songName: "last words", artist: "Isaac Gracie", lyrics: "fever rising in the setting sun cocaine in your eyes and bullets in your gun blood in your nails are you scratching for the fame? with a noose 'round your neck and a needle in your vein oh and you say how did I get here and can I get back?"},
    {songName: "The Unkillable Solider", artist: "Sabaton", lyrics: "into the fire through trenches and mud son of belgium and ireland with war in his blood leading the charge into hostile barrage by design he was made for the frontline never die shot through the eye never surrender however they try how they try shot through the eye he'll never die"},
    {songName: "The Middle", artist: "Jimmy Eat World", lyrics: "hey don't write yourself off yet it's only in your head you feel left out or looked down on just try your best try everything you can and don't you worry what they tell themselves when you're away it just takes some time little girl you're in the middle of the ride everything everything will be just fine everything everything will be alright alright"},
    {songName: "Oak Trees", artist: "Daniel Nunnelee", lyrics: "when I die will you put me under the earth under the oak trees and if I die before the sun rises i'll be just fine right where I am cause I know where I'm going i know where I'll be yeah, I know where I'm going so you don't cry about me cause I'll be dancing, I'll be singing i'll be spinning 'round in circles i'll be jumping, I'll be screaming when I see that silver lining and I hope that you'll be with me some day so don't cry about me cause I know where i'll be"},
    {songName: "Until the World Goes Cold", artist: "Trivium", lyrics: "i turned my back on everything i searched for half-remembered dreams pulling me down with you above my head, they're circling the vultures want what's left of me i sacrificed it all and I will fight until the world goes cold this battle's burned all that I've known until the world goes cold nothing will keep me from this throne, I'll fight until the world goes cold until the world goes cold"},
    {songName: "Earth Is a Black Hole", artist: "Teenage Wrist", lyrics: "i'm just a product of the afterglow the flower of the seed, the story you believe rolling with the undertow sucking on my teeth, waiting for my turn to speak i feel light and I feel free but I'm getting sick on the inside we are made to feel ashamed not every chemical is mixed right"},
    {songName: "Anxiety", artist: "Frank Carter & The Rattlesnakes", lyrics: "i don't know who I am everybody telling me they can't believe I can feel so depressed and unimpressed and be so stressed when I'm so blessed i got it all and they got less so sing this song with me and raise your hands and stamp your feet if you have got what you believe is a life full of anxiety and I'll tell you that it's okay 'cause it doesn't have to stay this way and there's a better place for you and me where we can be happy"},
    {songName: "Hey Hey, My, My (Into The Black)", artist: "Neil Young", lyrics: "hey hey, my my rock and roll can never die there's more to the picture than meets the eye hey hey, my my out of the blue and into the black you pay for this, but they give you that and once you're gone you can't come back when you're out of the blue and into the black the king is gone but he's not forgotten (Johnny Rotten, Johnny Rotten) is this the story of Johnny Rotten? (Johnny Rotten, Rotten Johnny) it's better to burn out 'cause rust never sleeps the king is gone but he's not forgotten hey hey, my my rock and roll can never die there's more to the picture than meets the eye"},
    {songName: "Life Eternal", artist: "Ghost", lyrics: "can you hear me say your name–forever? can you see me longing for you–forever? would you let me touch your soul–forever? can you feel me longing for you–forever, forever? i know the light grows darker down below but in your eyes, it's gone before you know this is the moment of just letting go she said, “If you had life eternal” can you hear me say your name–forever? can you see me longing for you–forever, forever? would you let me touch your soul–forever? can you feel me longing for you–forever, forever?"},
    {songName: "Socjopathetic", artist: "Daria Zawiałow", lyrics: "i lost my heart into that night before i lost myself the yellow light went through my eyes and then i felt embrace it wasn't dark but it was a guise hiding empty lights i lost my dyes into your black but first you've lost your heart this is endless war i don't have a gun it seems i'm blind sometimes i could be that guy sometimes i think i could fly and sometimes kiss for a while"},
    {songName: "Love Is For Losers", artist: "The Longshot",  lyrics: "i'm ridin' shotgun in a car that's broken down nowhere to run, and this city's like a ghost town and I'm feelin' like a stranger and I'm stranded in the dark hey kid, love is for losers now, alright stupid kid, you're a loser now, alright my heart's a has-been for my long lost valentine i searched the winter for the bride of Frankenstein well, we all got our delusions say goodbye to an old flame hey kid, love is for losers now, alright stupid kid, you're a loser now, alright get it out!"}
]